language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t talal89/docker-react-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true talal89/docker-react-client npm test -- --coverage

after_success:
  - docker build -t talal89/docker-react-client ./client
  - docker build -t talal89/docker-react-nginx ./nginx
  - docker build -t talal89/docker-react-server ./server
  - docker build -t talal89/docker-react-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  # PUSH the iamges to docker hub
  - docker push talal89/docker-react-client
  - docker push talal89/docker-react-nginx
  - docker push talal89/docker-react-server
  - docker push talal89/docker-react-worker

deploy:
  provider: elasticbeanstalk
  region: 'me-south-1'
  app: 'docker-multicontainer'
  env: 'DockerMulticontainer-env'
  bucket_name: 'elasticbeanstalk-me-south-1-488483174169'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY